source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.1"

group :development do
  gem 'minitest',             '5.18.0'
  gem 'minitest-byebug',      '0.0.3'
  gem 'rubocop',              '1.48.0'
  gem "rubycritic", require: false
end